/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZoneZoneRouteImport } from './routes/zone.$zone'
import { Route as SerrurierVilleRouteImport } from './routes/serrurier.$ville'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoneZoneRoute = ZoneZoneRouteImport.update({
  id: '/zone/$zone',
  path: '/zone/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const SerrurierVilleRoute = SerrurierVilleRouteImport.update({
  id: '/serrurier/$ville',
  path: '/serrurier/$ville',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/serrurier/$ville': typeof SerrurierVilleRoute
  '/zone/$zone': typeof ZoneZoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/serrurier/$ville': typeof SerrurierVilleRoute
  '/zone/$zone': typeof ZoneZoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/serrurier/$ville': typeof SerrurierVilleRoute
  '/zone/$zone': typeof ZoneZoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/serrurier/$ville' | '/zone/$zone'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/serrurier/$ville' | '/zone/$zone'
  id: '__root__' | '/' | '/serrurier/$ville' | '/zone/$zone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SerrurierVilleRoute: typeof SerrurierVilleRoute
  ZoneZoneRoute: typeof ZoneZoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone/$zone': {
      id: '/zone/$zone'
      path: '/zone/$zone'
      fullPath: '/zone/$zone'
      preLoaderRoute: typeof ZoneZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serrurier/$ville': {
      id: '/serrurier/$ville'
      path: '/serrurier/$ville'
      fullPath: '/serrurier/$ville'
      preLoaderRoute: typeof SerrurierVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SerrurierVilleRoute: SerrurierVilleRoute,
  ZoneZoneRoute: ZoneZoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
