/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZoneRouteImport } from './routes/$zone'
import { Route as ConditionsGeneralesRouteImport } from './routes/conditions-generales'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as ZoneVilleRouteImport } from './routes/$zone_.$ville'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoneRoute = ZoneRouteImport.update({
  id: '/$zone',
  path: '/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesRoute = ConditionsGeneralesRouteImport.update({
  id: '/conditions-generales',
  path: '/conditions-generales',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZoneVilleRoute = ZoneVilleRouteImport.update({
  id: '/$zone_/$ville',
  path: '/$zone/$ville',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$zone': typeof ZoneRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/$zone/$ville': typeof ZoneVilleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$zone': typeof ZoneRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/$zone/$ville': typeof ZoneVilleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$zone': typeof ZoneRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/$zone_/$ville': typeof ZoneVilleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$zone'
    | '/conditions-generales'
    | '/cookies'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/$zone/$ville'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$zone'
    | '/conditions-generales'
    | '/cookies'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/$zone/$ville'
  id:
    | '__root__'
    | '/'
    | '/$zone'
    | '/conditions-generales'
    | '/cookies'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/$zone_/$ville'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZoneRoute: typeof ZoneRoute
  ConditionsGeneralesRoute: typeof ConditionsGeneralesRoute
  CookiesRoute: typeof CookiesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  ZoneVilleRoute: typeof ZoneVilleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$zone': {
      id: '/$zone'
      path: '/$zone'
      fullPath: '/$zone'
      preLoaderRoute: typeof ZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales': {
      id: '/conditions-generales'
      path: '/conditions-generales'
      fullPath: '/conditions-generales'
      preLoaderRoute: typeof ConditionsGeneralesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$zone_/$ville': {
      id: '/$zone_/$ville'
      path: '/$zone/$ville'
      fullPath: '/$zone/$ville'
      preLoaderRoute: typeof ZoneVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZoneRoute: ZoneRoute,
  ConditionsGeneralesRoute: ConditionsGeneralesRoute,
  CookiesRoute: CookiesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  ZoneVilleRoute: ZoneVilleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
